---

# Update cache if older than 1 day (86400s)
- name: Make sure base packages are installed
  apt: name={{ item }} state={{ packages_state }}
       update_cache=yes cache_valid_time=86400
  with_items: common_packages.debian

- name: Make sure unwanted packages are removed
  apt: name={{ item }} state=absent
  with_items: common_packages_removed.debian

# vim: ft=ansible
