---
######################################################################
# Base packages
######################################################################

- include: Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - packages

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - packages

######################################################################
# Shell configuration
######################################################################

- name: Bash aliases
  lineinfile: dest="{{ item[0].home }}/.bashrc" state=present
              line="{{ item[1] }}"
  with_nested:
    - users
    - [
      "alias l='ls --color=auto -F -al'",
      "alias v=vim",
      ]
  tags:
    - common
    - bash

#=====================================================================
# Vim
#=====================================================================

- name: Vim configuration
  lineinfile: dest="{{ item[0].home }}/.vimrc" state=present
              line="{{ item[1] }}" create=yes
              owner="{{ item[0].name }}" group="{{ item[0].group | default(item[0].name) }}"
  with_nested:
    - users
    - [
      "set nocompatible hlsearch ignorecase smartcase showmatch",
      "set number list listchars=tab:>-,trail:-,nbsp:%",
      "set smartindent tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent",
      "set nojoinspaces mouse=a hidden",
      "color elflord",
      ]
  tags:
    - common
    - vim

#=====================================================================
# Liquidprompt
#=====================================================================

- name: Checkout Liquidprompt from Github
  git: repo=https://github.com/nojhan/liquidprompt.git
       dest=/opt/liquidprompt
  when: liquidprompt == true
  tags:
    - common
    - liquidprompt

# Current user
- name: Enable Liquidprompt
  lineinfile: line="source /opt/liquidprompt/liquidprompt"
              dest="{{ item.home }}/.bashrc" state=present
  with_items: users
  when: liquidprompt == true
  tags:
    - common
    - liquidprompt

- name: Configure Liquidprompt
  template: src="{{ item[1] }}" dest="{{ item[0].home }}/.{{ item[1] }}"
        owner="{{ item[0].name }}" group="{{ item[0].group | default(item[0].name) }}"
  with_nested:
    - users
    - [
      "liquidpromptrc",
      "liquid.theme",
      ]
  when: liquidprompt == true
  tags:
    - common
    - liquidprompt

# vim: ft=ansible
