---
######################################################################
# Base packages
######################################################################

# Update cache if older than 1 day (86400s)
- name: Make sure base packages are installed
  apt: name={{ item }} state={{ packages_state }}
       update_cache=yes cache_valid_time=86400
  with_items: common_packages
  tags:
    - common
    - packages

- name: Make sure unwanted packages are removed
  apt: name={{ item }} state=absent
  with_items: common_packages_removed
  tags:
    - common
    - packages

######################################################################
# Locale
######################################################################

# Fix for https://github.com/ansible/ansible/issues/7289
- name: Detect locales.gen file
  stat: path="{{ locales_gen_file }}"
  register: locales_gen_file_stats
  tags:
    - common
    - locale

# Fix for https://github.com/ansible/ansible/issues/7289
- name: Create locale.gen file
  file: path="{{ locales_gen_file }}" state=touch
  when: not locales_gen_file_stats.stat.exists
  tags:
    - common
    - locale

- name: Make sure wanted locales are present
  locale_gen: name="{{ item }}" state=present
  with_items: "{{ locales_list | default('en_US.UTF-8') }}"
  tags:
    - common
    - locale

- name: Set default Locale and Language
  lineinfile: line='export {{ item[0] }}="{{ item[1] }}"'
              regexp='^export {{ item[0] }}='
              dest=/etc/profile
              state=present create=yes
  with_nested:
    - [ 'LC_ALL', 'LANG' ]
    - "{{ locales_list[0] | default('en_US.UTF-8') }}"
  tags:
    - common
    - locale

######################################################################
# NTP
######################################################################

- name: be sure ntp is running and enabled
  service: name=ntp state=running enabled=yes
  tags:
    - common
    - time

######################################################################
# Timezone
######################################################################

- name: Set timezone
  lineinfile: line='{{ timezone | default('Etc/UTC') }}'
              regexp='^.*$'
              dest=/etc/timezone
              state=present create=yes
  notify: reconfigure tzdata
  tags:
    - common
    - time

######################################################################
# Shell configuration
######################################################################

- name: Bash aliases
  lineinfile: dest="{{ item[0].home }}/.bashrc" state=present
              line="{{ item[1] }}"
  with_nested:
    - users
    - [
      "alias l='ls --color=auto -F -al'",
      "alias v=vim",
      ]
  tags:
    - common
    - bash

#=====================================================================
# Vim
#=====================================================================

- name: Vim configuration
  lineinfile: dest="{{ item[0].home }}/.vimrc" state=present
              line="{{ item[1] }}" create=yes
              owner="{{ item[0].name }}" group="{{ item[0].group | default(item[0].name) }}"
  with_nested:
    - users
    - [
      "set nocompatible hlsearch ignorecase smartcase showmatch",
      "set number list listchars=tab:>-,trail:-,nbsp:%",
      "set smartindent tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent",
      "set nojoinspaces mouse=a hidden",
      "color elflord",
      ]
  tags:
    - common
    - vim

#=====================================================================
# Liquidprompt
#=====================================================================

- name: Checkout Liquidprompt from Github
  git: repo=https://github.com/nojhan/liquidprompt.git
       dest=/opt/liquidprompt
  when: liquidprompt == true
  tags:
    - common
    - liquidprompt

# Current user
- name: Enable Liquidprompt
  lineinfile: line="source /opt/liquidprompt/liquidprompt"
              dest="{{ item.home }}/.bashrc" state=present
  with_items: users
  when: liquidprompt == true
  tags:
    - common
    - liquidprompt

- name: Configure Liquidprompt
  copy: src="{{ item[1] }}" dest="{{ item[0].home }}/.{{ item[1] }}"
        owner="{{ item[0].name }}" group="{{ item[0].group | default(item[0].name) }}"
  with_nested:
    - users
    - [
      "liquidpromptrc",
      "liquid.theme",
      ]
  when: liquidprompt == true
  tags:
    - common
    - liquidprompt

# vim: ft=ansible
