Vagrant.configure("2") do |config|

  config.vm.define "test-common-ubuntu" do |node|
    node.vm.box = "ubuntu/trusty64"
    node.vm.hostname = "test-common-ubuntu.example.test"
    node.vm.network "public_network", bridge: "eth0"

    node.vm.provision "ansible" do |a|
      a.playbook = "test-vagrant.yml"
      a.sudo = true
    end
  end

  config.vm.define "test-common-centos" do |node|
    node.vm.box = "chef/centos-6.6"
    node.vm.hostname = "test-common-centos.example.test"
    node.vm.network "public_network", bridge: "eth0"

    node.vm.provision "ansible" do |a|
      a.playbook = "test-vagrant.yml"
      a.sudo = true
    end
  end

end
# vim: ft=ruby
