boxes = [
  { :name => "centos-7", :box => "chef/centos-7.0" },
  { :name => "centos-6", :box => "chef/centos-6.6" },
  { :name => "ubuntu-14", :box => "ubuntu/trusty64" },
  { :name => "debian-8", :box => "debian/jessie64" },
  { :name => "debian-7", :box => "chef/debian-7.8" },
]
Vagrant.configure("2") do |config|
  boxes.each_with_index do |box, index|
    config.vm.define box[:name] do |b|
      b.vm.box = box[:box]
      b.vm.hostname = box[:name]
      b.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", 256]
      end
      # The last VM is also used to provision all VMs at once.
      if index == boxes.length - 1
        b.vm.provision "ansible" do |a|
          a.playbook = "test.yml"
          a.sudo = true
          a.limit = 'all'
        end
      end
    end
  end
end
# vim: ft=ruby sw=2 sts=2
