---
# handlers file for common
# vim: ft=ansible

- name: restart ntp
  service: name=ntp state=restarted
  when: ansible_os_family == 'Debian'

- name: restart ntp
  service: name=ntpd state=restarted
  when: ansible_os_family == 'RedHat'

- name: reconfigure tzdata
  command: dpkg-reconfigure -f noninteractive tzdata
  when: ansible_os_family == 'Debian'

