---
# handlers file for common
# vim: ft=ansible

- name: restart ntp
  sudo: yes
  service: name=ntp state=restarted

- name: reconfigure tzdata
  sudo: yes
  command: dpkg-reconfigure -f noninteractive tzdata

